# APP CONFIGURATION
# Updates the package name and display name for your app

# Run in the terminal: "flutter pub run flutter_application_id:main"

flutter_application_id:
  android:
    id: "com.ewiglife.Earnerss"
    name: "Earnerss"
  ios:
    id: "com.ewiglife.Earnerss"
    name: "Earnerss"